services:
  - type: web
    name: teamone
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: NODE_ENV
        value: production
